# python data cleaning of sales analysis

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r'D:\Data Analytics\sales_analysis\dataset\Sales_Data.xlsx' , sheet_name='Sales Data')
df.head(5)

,Order ID,Year,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Client Segment,Country,...,Product Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Total Sales Amount,Purchasing Price,Total Purchasing Amounts,Net Profit
0,CA-2016-152156,2020.0,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.0,523.9200,157.17600,314.35200,209.56800
1,CA-2016-152156,2020.0,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.0,2195.8200,402.56700,1207.70100,988.11900
2,CA-2016-138688,2020.0,Jun,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.0,29.2400,8.77200,17.54400,11.69600
3,US-2015-108966,2020.0,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.0,4787.8875,478.78875,2393.94375,2393.94375
4,US-2015-108966,2020.0,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.0,35.7888,11.18400,22.36800,13.42080

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ' , '_')
df.columns

Index(['order_id', 'year', 'month', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'client_segment', 'country', 'state',
       'postal_code', 'region', 'product_id', 'product_category',
       'sub-category', 'product_name', 'sales_price', 'quantity', 'discount',
       'total_sales_amount', 'purchasing_price', 'total_purchasing_amounts',
       'net_profit'],
      dtype='object')

In [4]:
df.info()
print('=='*20)
print('null check')
print('=='*20)
print(df.isnull().sum())
print('=='*20)
print('duplicate check')
print('=='*20)
print(df.duplicated().sum())
print('=='*20)
print('data shape before cleaning')
print('=='*20)
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  1013 non-null   object
 1   year                      1013 non-null   float64
 2   month                     1013 non-null   object
 3   order_date                1011 non-null   datetime64[ns]
 4   ship_date                 1013 non-null   datetime64[ns]
 5   ship_mode                 1008 non-null   object
 6   customer_id               1013 non-null   object
 7   customer_name             1009 non-null   object
 8   client_segment            1013 non-null   object
 9   country                   1013 non-null   object
 10  state                     1013 non-null   object
 11  postal_code               1010 non-null   float64
 12  region                    1013 non-null   object
 13  product_id                1013 non-null   object
 14  product_category          1010 non-null   object
 15  sub-category              1013 non-null   object
 16  product_name              1013 non-null   object
 17  sales_price               1005 non-null   float64
 18  quantity                  1013 non-null   float64
 19  discount                  1013 non-null   float64
 20  total_sales_amount        1013 non-null   float64
 21  purchasing_price          1013 non-null   float64
 22  total_purchasing_amounts  1013 non-null   float64
 23  net_profit                1013 non-null   float64
dtypes: datetime64[ns](2), float64(9), object(13)
memory usage: 190.3+ KB
========================================
null check
========================================
order_id                    1
year                        1
month                       1
order_date                  3
ship_date                   1
ship_mode                   6
customer_id                 1
customer_name               5
client_segment              1
country                     1
state                       1
postal_code                 4
region                      1
product_id                  1
product_category            4
sub-category                1
product_name                1
sales_price                 9
quantity                    1
discount                    1
total_sales_amount          1
purchasing_price            1
total_purchasing_amounts    1
net_profit                  1
dtype: int64
========================================
duplicate check
========================================
7
========================================
data shape before cleaning
========================================
(1014, 24)

In [5]:
# sort missing 
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

sales_price                 9
ship_mode                   6
customer_name               5
postal_code                 4
product_category            4
order_date                  3
month                       1
order_id                    1
customer_id                 1
ship_date                   1
year                        1
country                     1
state                       1
region                      1
product_id                  1
client_segment              1
sub-category                1
product_name                1
quantity                    1
discount                    1
total_sales_amount          1
purchasing_price            1
total_purchasing_amounts    1
net_profit                  1
dtype: int64

* to check fully missing row

In [6]:
df[df.isnull().all(axis=1)]

,order_id,year,month,order_date,ship_date,ship_mode,customer_id,customer_name,client_segment,country,...,product_category,sub-category,product_name,sales_price,quantity,discount,total_sales_amount,purchasing_price,total_purchasing_amounts,net_profit
648,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* remove this full miss row

In [7]:
df = df.dropna(how='all').reset_index(drop=True)
print('data shape after remove full miss row')
df.shape

data shape after remove full miss row

(1013, 24)

* to check which row exact duplicate

In [8]:
# Display all rows involved in duplication
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,order_id,year,month,order_date,ship_date,ship_mode,customer_id,customer_name,client_segment,country,...,product_category,sub-category,product_name,sales_price,quantity,discount,total_sales_amount,purchasing_price,total_purchasing_amounts,net_profit
40,CA-2017-120999,2017.0,Sep,2017-09-10,2017-09-15,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,...,Technology,Phones,Panasonic Kx-TS550,147.168,4.0,0.0,470.9376,80.9424,323.7696,147.1680
179,CA-2014-158274,2014.0,Nov,2014-11-19,2014-11-24,Second Class,RM-19675,Robert Marley,Home Office,United States,...,Technology,Phones,Nokia Lumia 521 (T-Mobile),149.950,5.0,0.0,749.7500,74.9750,374.8750,374.8750
354,CA-2017-155698,2017.0,Mar,2017-03-08,2017-03-11,First Class,VB-21745,Victoria Brennan,Corporate,United States,...,Office Supplies,Appliances,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,647.840,8.0,0.0,5182.7200,421.0960,3368.7680,1813.9520
507,CA-2017-127432,2017.0,Jan,2017-01-22,2017-01-27,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,...,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,11.960,2.0,0.0,23.9200,8.3720,16.7440,7.1760
705,CA-2014-104472,2014.0,Jun,2014-06-02,2014-06-07,Standard Class,CK-12325,Christine Kargatis,Home Office,United States,...,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,59.808,3.0,0.0,143.5392,41.8656,125.5968,17.9424
872,CA-2015-143602,2015.0,Apr,2015-04-25,2015-04-28,Second Class,JS-15595,Jill Stevenson,Corporate,United States,...,Office Supplies,Binders,Fellowes Black Plastic Comb Bindings,13.944,3.0,0.0,33.4656,9.0636,27.1908,6.2748
997,CA-2014-158540,2014.0,Nov,2014-11-24,2014-11-26,First Class,VG-21790,Vivek Gonzalez,Consumer,United States,...,Furniture,Furnishings,"Eldon Delta Triangular Chair Mat, 52"" x 58"", C...",151.720,4.0,0.0,606.8800,91.0320,364.1280,242.7520
1006,CA-2017-120999,2017.0,Sep,2017-09-10,2017-09-15,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,...,Technology,Phones,Panasonic Kx-TS550,147.168,4.0,0.0,470.9376,80.9424,323.7696,147.1680
1007,CA-2014-158274,2014.0,Nov,2014-11-19,2014-11-24,Second Class,RM-19675,Robert Marley,Home Office,United States,...,Technology,Phones,Nokia Lumia 521 (T-Mobile),149.950,5.0,0.0,749.7500,74.9750,374.8750,374.8750
1008,CA-2017-155698,2017.0,Mar,2017-03-08,2017-03-11,First Class,VB-21745,Victoria Brennan,Corporate,United States,...,Office Supplies,Appliances,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,647.840,8.0,0.0,5182.7200,421.0960,3368.7680,1813.9520
1009,CA-2017-127432,2017.0,Jan,2017-01-22,2017-01-27,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,...,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,11.960,2.0,0.0,23.9200,8.3720,16.7440,7.1760
1010,CA-2014-104472,2014.0,Jun,2014-06-02,2014-06-07,Standard Class,CK-12325,Christine Kargatis,Home Office,United States,...,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,59.808,3.0,0.0,143.5392,41.8656,125.5968,17.9424
1011,CA-2015-143602,2015.0,Apr,2015-04-25,2015-04-28,Second Class,JS-15595,Jill Stevenson,Corporate,United States,...,Office Supplies,Binders,Fellowes Black Plastic Comb Bindings,13.944,3.0,0.0,33.4656,9.0636,27.1908,6.2748
1012,CA-2014-158540,2014.0,Nov,2014-11-24,2014-11-26,First Class,VG-21790,Vivek Gonzalez,Consumer,United States,...,Furniture,Furnishings,"Eldon Delta Triangular Chair Mat, 52"" x 58"", C...",151.720,4.0,0.0,606.8800,91.0320,364.1280,242.7520

* drop duplicate rows

In [9]:
# 1014 - 1 - 7
df = df.drop_duplicates().reset_index(drop=True)
print('after remove duplicate data shape')
df.shape

after remove duplicate data shape

(1006, 24)

* handle missing customer name

In [10]:
name_lookup = df.dropna(subset=['customer_name']).drop_duplicates('customer_id').set_index('customer_id')['customer_name']

df['customer_name'] = df['customer_name'].fillna(df['customer_id'].map(name_lookup))

df['customer_name'] = df['customer_name'].fillna('Unknown Customer')

df['customer_name'].isnull().sum()

np.int64(0)

* handle missing sale price

In [11]:
mask = df['sales_price'].isnull()
df.loc[mask, 'sales_price'] = df.loc[mask, 'total_sales_amount'] / df.loc[mask, 'quantity'] 

df['sales_price'].isnull().sum()

np.int64(0)

* handle missing ship mode

In [12]:
# For every order_id, find its first available ship_mode, then use that value to fill missing ship_mode values for the same order.
correct_ship_mode = (
    df.groupby('order_id')['ship_mode'].transform('first')
)

df['ship_mode'] = df['ship_mode'].fillna(correct_ship_mode)

* handle missing postal code

In [13]:
state_zip_mode = df.dropna(subset=['postal_code']).groupby('state')['postal_code'].agg(lambda x: x.mode()[0])
df['postal_code'] = df['postal_code'].fillna(df['state'].map(state_zip_mode))

df['postal_code'].isnull().sum()

np.int64(0)

* handle missing product category

In [14]:
cat_lookup = df.dropna(subset=['product_category']).drop_duplicates('sub-category').set_index('sub-category')['product_category']
df['product_category'] = df['product_category'].fillna(df['sub-category'].map(cat_lookup))

* handle missing order date

In [15]:
# For every order_id, find its first available order_date, then use that value to fill missing order_date values for the same order.
correct_order_date= (
    df.groupby('order_id')['order_date'].transform('first')
)

df['order_date'] = df['order_date'].fillna(correct_order_date)

df['order_date'].isnull().sum()

np.int64(0)

In [17]:
print('after handle null value :')
df.isnull().sum()

after handle null value :

order_id                    0
year                        0
month                       0
order_date                  0
ship_date                   0
ship_mode                   0
customer_id                 0
customer_name               0
client_segment              0
country                     0
state                       0
postal_code                 0
region                      0
product_id                  0
product_category            0
sub-category                0
product_name                0
sales_price                 0
quantity                    0
discount                    0
total_sales_amount          0
purchasing_price            0
total_purchasing_amounts    0
net_profit                  0
dtype: int64

In [21]:
df = df.rename(columns={'sub-category' :'sub_category'})
df.columns

Index(['order_id', 'year', 'month', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'client_segment', 'country', 'state',
       'postal_code', 'region', 'product_id', 'product_category',
       'sub_category', 'product_name', 'sales_price', 'quantity', 'discount',
       'total_sales_amount', 'purchasing_price', 'total_purchasing_amounts',
       'net_profit'],
      dtype='object')

* to check if negetive value exist in numeric_col

In [54]:
numeric_col = df.select_dtypes(include=('float64' , 'int64'))
check_cols = numeric_col.drop(columns=['discount','shipping_days'])

negative_rows = df[(check_cols <= 0).any(axis=1)]
negative_rows

# here use < 0 because in discount can possible 0 .

Empty DataFrame
Columns: [order_id, year, month, order_date, ship_date, ship_mode, customer_id, customer_name, client_segment, country, state, postal_code, region, product_id, product_category, sub_category, product_name, sales_price, quantity, discount, total_sales_amount, purchasing_price, total_purchasing_amounts, net_profit, shipping_days]
Index: []

[0 rows x 25 columns]

In [27]:
# remove white space from object 
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

In [28]:
# check unique values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    vals = df[col].unique()
    print(f"\n{col} ({len(vals)} unique): {sorted(vals)}")

order_id (488 unique): ['CA-2014-101476', 'CA-2014-103849', 'CA-2014-104269', 'CA-2014-104472', 'CA-2014-104976', 'CA-2014-105893', 'CA-2014-106376', 'CA-2014-106803', 'CA-2014-106810', 'CA-2014-107755', 'CA-2014-110072', 'CA-2014-111003', 'CA-2014-111451', 'CA-2014-112158', 'CA-2014-112326', 'CA-2014-113166', 'CA-2014-113362', 'CA-2014-113887', 'CA-2014-115259', 'CA-2014-115791', 'CA-2014-115812', 'CA-2014-117429', 'CA-2014-117639', 'CA-2014-118962', 'CA-2014-120887', 'CA-2014-122336', 'CA-2014-123260', 'CA-2014-123344', 'CA-2014-124429', 'CA-2014-125612', 'CA-2014-127488', 'CA-2014-127691', 'CA-2014-129924', 'CA-2014-130092', 'CA-2014-130960', 'CA-2014-131450', 'CA-2014-131926', 'CA-2014-132500', 'CA-2014-132962', 'CA-2014-133690', 'CA-2014-133753', 'CA-2014-133851', 'CA-2014-134061', 'CA-2014-134313', 'CA-2014-134677', 'CA-2014-135405', 'CA-2014-136742', 'CA-2014-138296', 'CA-2014-138527', 'CA-2014-139451', 'CA-2014-139892', 'CA-2014-140004', 'CA-2014-140795', 'CA-2014-140858', 'CA-2014-142048', 'CA-2014-143336', 'CA-2014-144407', 'CA-2014-144666', 'CA-2014-145576', 'CA-2014-146703', 'CA-2014-148488', 'CA-2014-149020', 'CA-2014-149958', 'CA-2014-151995', 'CA-2014-153150', 'CA-2014-154627', 'CA-2014-155208', 'CA-2014-155852', 'CA-2014-156314', 'CA-2014-156433', 'CA-2014-156601', 'CA-2014-157784', 'CA-2014-158274', 'CA-2014-158540', 'CA-2014-162775', 'CA-2014-163419', 'CA-2014-164259', 'CA-2014-164973', 'CA-2014-165974', 'CA-2014-166191', 'CA-2014-167164', 'CA-2014-167850', 'CA-2015-100454', 'CA-2015-101007', 'CA-2015-101910', 'CA-2015-102281', 'CA-2015-102848', 'CA-2015-105312', 'CA-2015-106320', 'CA-2015-106565', 'CA-2015-108665', 'CA-2015-109638', 'CA-2015-110457', 'CA-2015-110744', 'CA-2015-111164', 'CA-2015-111199', 'CA-2015-112319', 'CA-2015-112571', 'CA-2015-113173', 'CA-2015-114300', 'CA-2015-114923', 'CA-2015-115091', 'CA-2015-115742', 'CA-2015-115938', 'CA-2015-117415', 'CA-2015-118948', 'CA-2015-119291', 'CA-2015-119697', 'CA-2015-120880', 'CA-2015-122259', 'CA-2015-122756', 'CA-2015-124653', 'CA-2015-124891', 'CA-2015-124919', 'CA-2015-125395', 'CA-2015-126445', 'CA-2015-128139', 'CA-2015-128167', 'CA-2015-129098', 'CA-2015-129476', 'CA-2015-130736', 'CA-2015-130792', 'CA-2015-130883', 'CA-2015-130890', 'CA-2015-131128', 'CA-2015-131457', 'CA-2015-131534', 'CA-2015-132906', 'CA-2015-133025', 'CA-2015-133627', 'CA-2015-134782', 'CA-2015-134894', 'CA-2015-135272', 'CA-2015-135545', 'CA-2015-137225', 'CA-2015-137946', 'CA-2015-138009', 'CA-2015-140921', 'CA-2015-142027', 'CA-2015-143602', 'CA-2015-144253', 'CA-2015-144267', 'CA-2015-145352', 'CA-2015-146262', 'CA-2015-146563', 'CA-2015-146829', 'CA-2015-147851', 'CA-2015-148250', 'CA-2015-149587', 'CA-2015-149713', 'CA-2015-149734', 'CA-2015-153549', 'CA-2015-154144', 'CA-2015-154620', 'CA-2015-154921', 'CA-2015-155040', 'CA-2015-155334', 'CA-2015-157035', 'CA-2015-157812', 'CA-2015-158792', 'CA-2015-160059', 'CA-2015-162537', 'CA-2015-163055', 'CA-2015-168004', 'CA-2015-169397', 'CA-2016-100153', 'CA-2016-100790', 'CA-2016-101343', 'CA-2016-103730', 'CA-2016-103891', 'CA-2016-103947', 'CA-2016-105018', 'CA-2016-105256', 'CA-2016-105494', 'CA-2016-105585', 'CA-2016-105760', 'CA-2016-105816', 'CA-2016-106075', 'CA-2016-106341', 'CA-2016-108987', 'CA-2016-109806', 'CA-2016-109869', 'CA-2016-110023', 'CA-2016-110366', 'CA-2016-110499', 'CA-2016-110772', 'CA-2016-111010', 'CA-2016-111682', 'CA-2016-112697', 'CA-2016-112942', 'CA-2016-113243', 'CA-2016-113747', 'CA-2016-113817', 'CA-2016-114104', 'CA-2016-114489', 'CA-2016-114713', 'CA-2016-115504', 'CA-2016-115756', 'CA-2016-115917', 'CA-2016-116736', 'CA-2016-117590', 'CA-2016-118255', 'CA-2016-119823', 'CA-2016-120180', 'CA-2016-120859', 'CA-2016-121223', 'CA-2016-121755', 'CA-2016-123274', 'CA-2016-123666', 'CA-2016-125318', 'CA-2016-126158', 'CA-2016-126613', 'CA-2016-127208', 'CA-2016-127250', 'CA-2016-127369', 'CA-2016-128867', 'CA-2016-129714', 'CA-2016-129903', 'CA-2016-130001', 'CA-2016-130162', 'CA-2016-130477', 'CA-2016-132661', 'CA-2016-134362', 'CA-2016-134474', 'CA-2016-134775', 'CA-2016-136133', 'CA-2016-136406', 'CA-2016-136924', 'CA-2016-137239', 'CA-2016-137330', 'CA-2016-138520', 'CA-2016-138688', 'CA-2016-140081', 'CA-2016-140634', 'CA-2016-140928', 'CA-2016-142335', 'CA-2016-142545', 'CA-2016-142902', 'CA-2016-142958', 'CA-2016-143308', 'CA-2016-144939', 'CA-2016-145499', 'CA-2016-145583', 'CA-2016-145625', 'CA-2016-146941', 'CA-2016-147067', 'CA-2016-147375', 'CA-2016-148796', 'CA-2016-149223', 'CA-2016-149370', 'CA-2016-149797', 'CA-2016-150889', 'CA-2016-152156', 'CA-2016-152534', 'CA-2016-152632', 'CA-2016-154508', 'CA-2016-154739', 'CA-2016-155488', 'CA-2016-155516', 'CA-2016-157000', 'CA-2016-157245', 'CA-2016-157749', 'CA-2016-158099', 'CA-2016-158568', 'CA-2016-158834', 'CA-2016-159695', 'CA-2016-160745', 'CA-2016-161389', 'CA-2016-161669', 'CA-2016-161816', 'CA-2016-162138', 'CA-2016-162733', 'CA-2016-163755', 'CA-2016-164511', 'CA-2016-165148', 'CA-2016-165218', 'CA-2016-165316', 'CA-2016-166674', 'CA-2016-168753', 'CA-2016-169166', 'CA-2016-169194', 'CA-2017-100314', 'CA-2017-100650', 'CA-2017-101434', 'CA-2017-101798', 'CA-2017-101945', 'CA-2017-102414', 'CA-2017-102519', 'CA-2017-102946', 'CA-2017-104220', 'CA-2017-104745', 'CA-2017-105074', 'CA-2017-105809', 'CA-2017-106103', 'CA-2017-106180', 'CA-2017-107503', 'CA-2017-107720', 'CA-2017-107727', 'CA-2017-108329', 'CA-2017-108910', 'CA-2017-110478', 'CA-2017-111178', 'CA-2017-111689', 'CA-2017-112774', 'CA-2017-113558', 'CA-2017-114216', 'CA-2017-114412', 'CA-2017-114440', 'CA-2017-114552', 'CA-2017-114636', 'CA-2017-115364', 'CA-2017-117240', 'CA-2017-117457', 'CA-2017-117933', 'CA-2017-117947', 'CA-2017-118136', 'CA-2017-118437', 'CA-2017-118640', 'CA-2017-118731', 'CA-2017-119004', 'CA-2017-119305', 'CA-2017-120999', 'CA-2017-122105', 'CA-2017-125388', 'CA-2017-126046', 'CA-2017-126074', 'CA-2017-126221', 'CA-2017-126382', 'CA-2017-126774', 'CA-2017-126956', 'CA-2017-127432', 'CA-2017-129462', 'CA-2017-129567', 'CA-2017-130043', 'CA-2017-130351', 'CA-2017-131156', 'CA-2017-131954', 'CA-2017-132353', 'CA-2017-132682', 'CA-2017-132934', 'CA-2017-132976', 'CA-2017-133256', 'CA-2017-133333', 'CA-2017-133431', 'CA-2017-134306', 'CA-2017-134978', 'CA-2017-135034', 'CA-2017-135279', 'CA-2017-135307', 'CA-2017-135783', 'CA-2017-135860', 'CA-2017-136539', 'CA-2017-136826', 'CA-2017-137099', 'CA-2017-137596', 'CA-2017-138611', 'CA-2017-139619', 'CA-2017-140088', 'CA-2017-140844', 'CA-2017-140963', 'CA-2017-142636', 'CA-2017-143259', 'CA-2017-143686', 'CA-2017-144113', 'CA-2017-144694', 'CA-2017-144904', 'CA-2017-144932', 'CA-2017-145142', 'CA-2017-145233', 'CA-2017-146136', 'CA-2017-146780', 'CA-2017-147277', 'CA-2017-149160', 'CA-2017-150707', 'CA-2017-150959', 'CA-2017-151428', 'CA-2017-152142', 'CA-2017-152275', 'CA-2017-153339', 'CA-2017-153787', 'CA-2017-154214', 'CA-2017-154816', 'CA-2017-155376', 'CA-2017-155558', 'CA-2017-155698', 'CA-2017-155705', 'CA-2017-156951', 'CA-2017-157252', 'CA-2017-157833', 'CA-2017-159366', 'CA-2017-160514', 'CA-2017-160983', 'CA-2017-161018', 'CA-2017-161480', 'CA-2017-161984', 'CA-2017-162929', 'CA-2017-163020', 'CA-2017-163139', 'CA-2017-163405', 'CA-2017-163979', 'CA-2017-164826', 'CA-2017-165603', 'CA-2017-167899', 'CA-2017-167913', 'CA-2017-169901', 'US-2014-100853', 'US-2014-102071', 'US-2014-105767', 'US-2014-106992', 'US-2014-110674', 'US-2014-111171', 'US-2014-115987', 'US-2014-117135', 'US-2014-119137', 'US-2014-134614', 'US-2014-134971', 'US-2014-135972', 'US-2014-141215', 'US-2014-147606', 'US-2014-150574', 'US-2014-152030', 'US-2014-156216', 'US-2014-158638', 'US-2015-101399', 'US-2015-101511', 'US-2015-108966', 'US-2015-118983', 'US-2015-120161', 'US-2015-120712', 'US-2015-126214', 'US-2015-134026', 'US-2015-136476', 'US-2015-138303', 'US-2015-140200', 'US-2015-145436', 'US-2015-150630', 'US-2015-156867', 'US-2015-157014', 'US-2015-159982', 'US-2015-161991', 'US-2015-164175', 'US-2015-168935', 'US-2016-100419', 'US-2016-100720', 'US-2016-105578', 'US-2016-114622', 'US-2016-120929', 'US-2016-123470', 'US-2016-123750', 'US-2016-125969', 'US-2016-134656', 'US-2016-135720', 'US-2016-137547', 'US-2016-139486', 'US-2016-141544', 'US-2016-146710', 'US-2016-150147', 'US-2016-150861', 'US-2016-156097', 'US-2016-156986', 'US-2016-157945', 'US-2017-100048', 'US-2017-100209', 'US-2017-100930', 'US-2017-103247', 'US-2017-106663', 'US-2017-106705', 'US-2017-107272', 'US-2017-109484', 'US-2017-110576', 'US-2017-111745', 'US-2017-116701', 'US-2017-118038', 'US-2017-119438', 'US-2017-119662', 'US-2017-122637', 'US-2017-123463', 'US-2017-124303', 'US-2017-127719', 'US-2017-129441', 'US-2017-145366', 'US-2017-152366', 'US-2017-152380', 'US-2017-155299', 'US-2017-156083', 'US-2017-156909', 'US-2017-164147', 'US-2017-168116']

month (12 unique): ['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep']

ship_mode (4 unique): ['First Class', 'Same Day', 'Second Class', 'Standard Class']

customer_id (366 unique): ['AA-10375', 'AA-10480', 'AB-10060', 'AB-10165', 'AC-10420', 'AD-10180', 'AF-10885', 'AG-10270', 'AG-10495', 'AG-10525', 'AG-10675', 'AG-10765', 'AG-10900', 'AH-10075', 'AH-10195', 'AH-10210', 'AJ-10780', 'AJ-10795', 'AJ-10945', 'AJ-10960', 'AM-10360', 'AP-10915', 'AR-10405', 'AR-10510', 'AR-10825', 'AS-10135', 'AS-10225', 'AS-10240', 'AS-10285', 'AS-10630', 'AT-10735', 'BB-10990', 'BB-11545', 'BD-11320', 'BD-11500', 'BD-11605', 'BD-11725', 'BE-11335', 'BF-11020', 'BH-11710', 'BK-11260', 'BM-11140', 'BM-11650', 'BM-11785', 'BN-11470', 'BN-11515', 'BP-11095', 'BP-11185', 'BS-11590', 'BS-11755', 'BS-11800', 'BV-11245', 'BW-11110', 'CA-12265', 'CA-12310', 'CA-12775', 'CB-12025', 'CB-12535', 'CC-12145', 'CC-12430', 'CC-12550', 'CC-12670', 'CD-11920', 'CD-11980', 'CG-12040', 'CG-12520', 'CJ-12010', 'CK-12205', 'CK-12325', 'CK-12595', 'CK-12760', 'CL-12565', 'CM-12385', 'CM-12445', 'CP-12340', 'CR-12625', 'CR-12730', 'CS-11950', 'CS-12130', 'CS-12250', 'CS-12400', 'CV-12805', 'CW-11905', 'DB-13060', 'DB-13120', 'DB-13210', 'DB-13615', 'DC-13285', 'DJ-13420', 'DJ-13510', 'DJ-13630', 'DK-12985', 'DK-13090', 'DK-13150', 'DK-13225', 'DL-12865', 'DL-12925', 'DL-13315', 'DN-13690', 'DO-13435', 'DP-13000', 'DP-13105', 'DP-13165', 'DR-12880', 'DS-13030', 'DS-13180', 'DV-13045', 'DV-13465', 'DW-13480', 'DW-13585', 'Dl-13600', 'EA-14035', 'EB-13705', 'EB-13840', 'EB-13870', 'EG-13900', 'EH-13945', 'EH-14125', 'EL-13735', 'EM-13960', 'EM-14065', 'EM-14095', 'EP-13915', 'ER-13855', 'ES-14020', 'ES-14080', 'FA-14230', 'FH-14365', 'FM-14290', 'FM-14380', 'FP-14320', 'GA-14725', 'GB-14530', 'GD-14590', 'GG-14650', 'GH-14485', 'GH-14665', 'GK-14620', 'GM-14440', 'GM-14455', 'GP-14740', 'GT-14635', 'GT-14710', 'GT-14755', 'GZ-14470', 'HA-14920', 'HK-14890', 'HL-15040', 'HM-14980', 'HP-14815', 'HW-14935', 'IM-15070', 'JA-15970', 'JB-15400', 'JB-15925', 'JC-15340', 'JC-16105', 'JD-15895', 'JD-16060', 'JD-16150', 'JE-15475', 'JE-15745', 'JE-16165', 'JF-15355', 'JF-15415', 'JF-15490', 'JG-15115', 'JG-15805', 'JH-15910', 'JH-15985', 'JJ-15760', 'JK-15370', 'JK-15640', 'JK-15730', 'JL-15175', 'JL-15505', 'JL-15835', 'JL-15850', 'JM-15250', 'JM-15265', 'JM-15535', 'JO-15280', 'JO-15550', 'JP-15520', 'JR-16210', 'JS-15595', 'JS-15685', 'JS-15880', 'JS-15940', 'KB-16240', 'KB-16315', 'KB-16585', 'KB-16600', 'KC-16255', 'KC-16540', 'KC-16675', 'KD-16270', 'KD-16345', 'KH-16360', 'KH-16510', 'KH-16630', 'KH-16690', 'KL-16555', 'KL-16645', 'KM-16225', 'KM-16720', 'KW-16435', 'LA-16780', 'LC-16870', 'LC-16885', 'LC-16930', 'LC-17140', 'LE-16810', 'LF-17185', 'LH-16900', 'LH-17020', 'LH-17155', 'LL-16840', 'LM-17065', 'LP-17080', 'LR-16915', 'LS-16945', 'LS-16975', 'LS-17245', 'LT-17110', 'LW-16990', 'MA-17560', 'MB-17305', 'MC-17605', 'MC-17845', 'MC-18130', 'MD-17350', 'ME-17725', 'MG-17680', 'MG-18145', 'MH-17785', 'MJ-17740', 'MK-17905', 'MK-18160', 'MM-18280', 'MO-17800', 'MP-17470', 'MP-17965', 'MR-17545', 'MS-17365', 'MS-17830', 'MS-17980', 'MT-17815', 'MT-18070', 'MV-18190', 'MW-18235', 'MY-17380', 'MZ-17515', 'NB-18655', 'NF-18385', 'NG-18355', 'NK-18490', 'NM-18445', 'NP-18325', 'NP-18670', 'NZ-18565', 'ON-18715', 'OT-18730', 'PA-19060', 'PB-19105', 'PB-19150', 'PC-18745', 'PF-19165', 'PG-18820', 'PG-18895', 'PH-18790', 'PJ-19015', 'PK-18910', 'PK-19075', 'PM-19135', 'PN-18775', 'PO-18850', 'PO-18865', 'PO-19180', 'PO-19195', 'PS-18970', 'RA-19285', 'RA-19885', 'RA-19915', 'RA-19945', 'RB-19360', 'RB-19465', 'RB-19570', 'RB-19705', 'RB-19795', 'RC-19825', 'RC-19960', 'RD-19585', 'RD-19810', 'RD-19900', 'RF-19735', 'RF-19840', 'RH-19495', 'RK-19300', 'RL-19615', 'RM-19675', 'RO-19780', 'RP-19270', 'RP-19390', 'RS-19765', 'RW-19630', 'RW-19690', 'SA-20830', 'SB-20290', 'SC-20050', 'SC-20095', 'SC-20305', 'SC-20695', 'SC-20725', 'SC-20770', 'SD-20485', 'SE-20110', 'SF-20065', 'SF-20200', 'SF-20965', 'SG-20080', 'SH-19975', 'SH-20395', 'SJ-20125', 'SJ-20500', 'SK-19990', 'SL-20155', 'SM-20005', 'SN-20710', 'SO-20335', 'SP-20545', 'SP-20650', 'SP-20860', 'SR-20740', 'SS-20140', 'SS-20590', 'SS-20875', 'SV-20365', 'SW-20275', 'TB-21055', 'TB-21190', 'TB-21520', 'TB-21595', 'TD-20995', 'TG-21640', 'TH-21235', 'TH-21550', 'TN-21040', 'TP-21130', 'TR-21325', 'TS-21205', 'TS-21340', 'TS-21610', 'TT-21070', 'TW-21025', 'TZ-21580', 'VB-21745', 'VD-21670', 'VG-21790', 'VM-21685', 'VP-21730', 'VW-21775', 'XP-21865', 'YC-21895', 'ZC-21910', 'ZD-21925']

customer_name (366 unique): ['Adam Bellavance', 'Adam Hart', 'Adrian Shami', 'Alan Barnes', 'Alan Dominguez', 'Alan Haines', 'Alan Hwang', 'Alan Schoenberger', 'Alan Shonely', 'Alejandro Grove', 'Alejandro Savely', 'Alice McCarthy', 'Allen Armold', 'Allen Rosenblatt', 'Alyssa Crouse', 'Andrew Allen', 'Andrew Gjertsen', 'Andrew Roberts', 'Andy Gerbode', 'Ann Steele', 'Anna Gayman', 'Annie Thurman', 'Anthony Garverick', 'Anthony Jacobs', 'Anthony Johnson', 'Anthony Rawles', 'Art Foster', 'Arthur Gainer', 'Arthur Prichep', 'Ashley Jarboe', 'Astrea Jones', 'Barry Blumstein', 'Barry Französisch', 'Bart Pistole', 'Bart Watters', 'Becky Martin', 'Ben Peterman', 'Benjamin Venier', 'Berenike Kampe', 'Bill Donatelli', 'Bill Eplett', 'Brad Norvell', 'Bradley Drucker', 'Bradley Nguyen', 'Brenda Bowman', 'Brendan Sweed', 'Brian Dahlen', 'Brian Moss', 'Brosina Hoffman', 'Bruce Degenhardt', 'Bruce Stewart', 'Bryan Mills', 'Bryan Spruell', 'Carl Weiss', 'Carlos Daly', 'Carlos Soltero', 'Carol Darley', 'Caroline Jumper', 'Cassandra Brandow', 'Catherine Glotzbach', 'Chad Sievert', 'Charles Crestani', 'Chloris Kastensmidt', 'Chris Selesnick', 'Christina Anderson', 'Christine Abelman', 'Christine Kargatis', 'Christine Phan', 'Christopher Martinez', 'Christopher Schild', 'Chuck Clark', 'Chuck Magee', 'Claire Gute', 'Claudia Bergmann', 'Clay Cheatham', 'Clay Ludtke', 'Clytie Kelty', 'Corey Roper', 'Craig Carreira', 'Craig Reiter', 'Cyma Kinney', 'Cynthia Arntzen', 'Cynthia Voltz', 'Dan Lawera', 'Dan Reichenbach', 'Daniel Lacy', 'Darren Koutras', 'Darren Powers', 'Darrin Sayre', 'Darrin Van Huff', 'Dave Brooks', 'Dave Kipp', 'Dave Poirier', 'David Bremer', 'David Kendrick', 'David Philippe', 'David Smith', 'Dean Braden', 'Dean Katz', 'Debra Catini', 'Delfina Latchford', 'Denny Joy', 'Denny Ordway', 'Dianna Vittorini', 'Dianna Wilson', 'Don Jones', 'Dorothy Wardle', 'Dorris liebe', 'Doug Bickford', 'Doug Jacobs', 'Duane Noonan', 'Ed Braxton', 'Ed Ludwig', 'Ellis Ballard', 'Elpida Rittenbach', 'Emily Burns', 'Emily Grady', 'Emily Phan', 'Eric Hoffmann', 'Eric Murdock', 'Erica Smith', 'Erin Ashbrook', 'Erin Mull', 'Erin Smith', 'Eudokia Martin', 'Eugene Hildebrand', 'Frank Atkinson', 'Frank Merwin', 'Frank Preis', 'Fred Hopkins', 'Fred McMath', 'Gary McGarr', 'Gary Mitchum', 'Gary Zandusky', 'Gene Hale', 'George Bell', 'Giulietta Dortch', 'Grace Kelly', 'Grant Thornton', 'Greg Guthrie', 'Greg Hansen', 'Greg Tran', 'Guy Armstrong', 'Guy Phonely', 'Guy Thornton', 'Harold Pawlan', 'Heather Kirkland', 'Helen Andreada', 'Helen Wasserman', 'Henry MacAllister', 'Hunter Lopez', 'Irene Maddox', 'Jack Garza', 'James Lanier', 'Janet Martin', 'Janet Molinari', "Jas O'Carroll", 'Jasper Cacioppo', 'Jay Fein', 'Jay Kimmel', 'Jennifer Braxton', 'Jennifer Ferguson', 'Jeremy Ellison', 'Jeremy Farry', 'Jeremy Lonsdale', 'Jeremy Pistek', 'Jessica Myrick', 'Jesus Ocampo', 'Jill Stevenson', 'Jim Kriz', 'Jim Sink', 'Joe Kamberova', 'Joel Eaton', 'Joel Jenkins', 'John Grady', 'John Lee', 'John Lucas', 'John Stevenson', 'Jonathan Doherty', 'Jonathan Howell', 'Joni Blumstein', 'Joni Sundaresam', 'Joseph Airdo', 'Joseph Holt', 'Julia Dunbar', 'Julie Creighton', 'Justin Deggeller', 'Justin Ellison', 'Justin Ritter', 'Kalyca Meade', 'Karen Bern', 'Karen Carlisle', 'Karen Daniels', 'Karl Braun', 'Katherine Ducich', 'Katherine Hughes', 'Katrina Willman', 'Keith Herrera', 'Kelly Collister', 'Kelly Lampkin', 'Ken Black', 'Ken Brennan', 'Ken Heidel', 'Ken Lonsdale', 'Kimberly Carter', 'Kristen Hastings', 'Kunst Miller', 'Laura Armstrong', 'Laurel Elliston', 'Lauren Leatherbury', 'Lena Cacioppo', 'Lena Creighton', 'Lena Hernandez', 'Lena Radford', 'Linda Cazamias', 'Linda Southworth', 'Lindsay Shagiari', 'Lindsay Williams', 'Lisa Hazard', 'Liz MacKendrick', 'Liz Pelletier', 'Liz Thompson', 'Logan Currie', 'Logan Haushalter', 'Luke Foster', 'Lynn Smith', 'Maria Bertelson', 'Maribeth Dona', 'Maribeth Schnelling', 'Maribeth Yedwab', 'Mark Packer', 'Mary Zewe', 'Mathew Reese', 'Matt Abelman', 'Matt Connell', 'Maureen Gastineau', 'Max Engle', 'Max Jones', 'Maya Herman', "Meg O'Connel", 'Meg Tillman', 'Melanie Seite', 'Michael Chen', 'Michael Kennedy', 'Michael Paige', 'Michael Stewart', 'Michelle Tran', 'Mike Caudle', 'Mike Gockenbach', 'Mike Kennedy', 'Mike Vittorini', 'Mitch Willingham', 'Muhammed MacIntyre', 'Naresj Patel', 'Nat Gilpin', 'Natalie Fritzler', 'Nathan Mautz', 'Neil Knudson', 'Nick Zandusky', 'Nona Balk', 'Nora Paige', 'Odella Nelson', 'Olvera Toch', 'Pamela Coakley', 'Parhena Norris', 'Patricia Hirasaki', 'Patrick Gardner', "Patrick O'Brill", "Patrick O'Donnell", 'Paul Gonzalez', 'Paul Knutson', 'Paul Stevenson', 'Pauline Johnson', 'Pete Armstrong', 'Pete Kriz', 'Peter Bühler', 'Peter McVee', 'Philip Brown', 'Philip Fox', 'Philisse Overcash', 'Phillina Ober', 'Rachel Payne', 'Ralph Arnett', 'Ralph Kennedy', 'Raymond Buch', 'Resi Pölking', 'Rick Bensley', 'Rick Hansen', 'Rob Beeghly', 'Rob Dowd', 'Rob Lucas', 'Rob Williams', 'Robert Marley', 'Robert Waldorf', 'Roger Barcio', 'Roland Fjeld', 'Roland Schwarz', "Rose O'Brian", 'Ross Baird', 'Ross DeVincentis', 'Roy Collins', 'Roy Französisch', 'Ruben Ausman', 'Ruben Dartt', 'Russell Applegate', 'Ryan Akin', 'Ryan Crowe', 'Sally Hughsby', 'Sally Knutson', 'Sally Matthias', 'Sample Company A', 'Sandra Flanagan', 'Sandra Glassco', 'Sanjit Chand', 'Sanjit Engle', 'Sanjit Jacobs', 'Saphhira Shifley', 'Sara Luxemburg', 'Scott Williamson', 'Sean Braxton', 'Sean Christensen', "Sean O'Donnell", 'Seth Vernon', 'Shahid Hopkins', 'Shirley Daniels', 'Shirley Jackson', 'Sibella Parks', 'Sonia Sunley', 'Stephanie Phelps', 'Steve Chapman', 'Steve Nguyen', 'Steven Cartwright', 'Steven Roelle', 'Stewart Carmichael', 'Sue Ann Reed', 'Sung Pak', 'Sung Shariari', 'Sylvia Foulston', 'Tamara Dahlen', 'Tamara Willingham', 'Tanja Norvell', 'Ted Butterfield', 'Ted Trevino', 'Theone Pippenger', 'Thomas Brumley', 'Thomas Seio', 'Tiffany House', 'Toby Ritter', 'Toby Swindell', 'Tracy Blumstein', 'Tracy Hopkins', 'Tracy Zic', 'Troy Blackwell', 'Troy Staebel', 'Trudy Glocke', 'Unknown Customer', 'Valerie Dominguez', 'Valerie Mitchum', 'Victor Preis', 'Victoria Brennan', 'Victoria Wilson', 'Vivek Gonzalez', 'Xylona Preis', 'Yoseph Carroll', 'Zuschuss Carroll', 'Zuschuss Donatelli']

client_segment (3 unique): ['Consumer', 'Corporate', 'Home Office']

country (1 unique): ['United States']


* to check year column and order year consistency

In [41]:
year_from_order_date = df['order_date'].dt.year

missmatch = df['year'] != year_from_order_date
print(f'year missmatch for year column and order date col : {missmatch.sum()}')

# Preview rows where Year disagrees with Order Date
df.loc[
    missmatch,
    ['order_id', 'year', 'order_date']
].assign(
    Correct_Year=year_from_order_date[missmatch]
).head(10)

year missmatch for year column and order date col : 26

         order_id    year order_date  Correct_Year
0  CA-2016-152156  2020.0 2016-11-08          2016
1  CA-2016-152156  2020.0 2016-11-08          2016
2  CA-2016-138688  2020.0 2016-06-12          2016
3  US-2015-108966  2020.0 2015-10-11          2015
4  US-2015-108966  2020.0 2015-10-11          2015
5  CA-2014-115812  2020.0 2014-06-09          2014
6  CA-2014-115812  2020.0 2014-06-09          2014
7  CA-2014-115812  2020.0 2014-06-09          2014
8  CA-2014-115812  2020.0 2014-06-09          2014
9  CA-2014-115812  2020.0 2014-06-09          2014

In [44]:
# Correct Year using the trusted Order Date column
df['year'] = df['order_date'].dt.year

# Confirm that all Year values now match Order Date
year_mismatch_after = (
    df['year'] != df['order_date'].dt.year
).sum()

print("Year Mismatches After Cleaning:", year_mismatch_after)

Year Mismatches After Cleaning: 0

* here discount column all value are 0 that is complete wrong so need to calculate proper discount

In [61]:
df['discount'] = 1 - (df['total_sales_amount'] / (df['sales_price'] * df['quantity']))
df['discount'] = df['discount'].round(2) 
df['discount'].value_counts()

discount
0.00    609
0.20    374
0.30      9
0.10      9
0.15      3
0.32      2
Name: count, dtype: int64

In [64]:
# now check total sale amount = sale price * qty - discount check data consistency
calculated_total = (
    df['sales_price'] * df['quantity']
) - df['discount']

mismatch = ~np.isclose(
    df['total_sales_amount'],
    calculated_total,
    rtol=0,
    atol=0.01
)

inconsistent_rows = df[mismatch]

inconsistent_rows
print(f"Truly inconsistent rows (can't be explained by price x qty x discount): {mismatch.sum()}")
print(f"Rows where original 'discount' column was just wrong: {(df['discount'] != df['discount']).sum()}")

Truly inconsistent rows (can't be explained by price x qty x discount): 397
Rows where original 'discount' column was just wrong: 0

In [68]:
# now check net profit = total sale amount - total purchase amount
#  check data consistency
calculated_profit = df['total_sales_amount'] - df['total_purchasing_amounts']

mismatch = ~np.isclose(
    df['net_profit'],
    calculated_profit,
    rtol=0,
    atol=0.01
)

inconsistent_rows = df[mismatch]

inconsistent_rows

Empty DataFrame
Columns: [order_id, year, month, order_date, ship_date, ship_mode, customer_id, customer_name, client_segment, country, state, postal_code, region, product_id, product_category, sub_category, product_name, sales_price, quantity, discount, total_sales_amount, purchasing_price, total_purchasing_amounts, net_profit, shipping_days, profit_margin_%]
Index: []

[0 rows x 26 columns]

* create a new column

In [69]:
df['shipping_days'] = (df['ship_date']-df['order_date']).dt.days
df['profit_margin_%'] = (df['net_profit'] / df['total_sales_amount']) * 100

In [70]:
df

,order_id,year,month,order_date,ship_date,ship_mode,customer_id,customer_name,client_segment,country,...,product_name,sales_price,quantity,discount,total_sales_amount,purchasing_price,total_purchasing_amounts,net_profit,shipping_days,profit_margin_%
0,CA-2016-152156,2016,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Bush Somerset Collection Bookcase,261.9600,2.0,0.0,523.9200,157.17600,314.35200,209.56800,3,40.0
1,CA-2016-152156,2016,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.0,2195.8200,402.56700,1207.70100,988.11900,3,45.0
2,CA-2016-138688,2016,Jun,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.0,29.2400,8.77200,17.54400,11.69600,4,40.0
3,US-2015-108966,2015,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.0,4787.8875,478.78875,2393.94375,2393.94375,7,50.0
4,US-2015-108966,2015,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.2,35.7888,11.18400,22.36800,13.42080,7,37.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,US-2015-126214,2015,Dec,2015-12-21,2015-12-24,Second Class,JS-15880,John Stevenson,Consumer,United States,...,Enermax Acrylux Wireless Keyboard,99.6000,1.0,0.0,99.6000,49.80000,49.80000,49.80000,3,50.0
1002,CA-2015-133025,2015,Sep,2015-09-17,2015-09-19,Second Class,MO-17800,Meg O'Connel,Home Office,United States,...,Xerox 216,32.4000,5.0,0.0,162.0000,21.06000,105.30000,56.70000,2,35.0
1003,CA-2015-108665,2015,Jul,2015-07-06,2015-07-10,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,...,G.E. Halogen Desk Lamp Bulbs,13.9600,2.0,0.0,27.9200,8.37600,16.75200,11.16800,4,40.0
1004,CA-2015-108665,2015,Jul,2015-07-06,2015-07-10,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,...,"Howard Miller 11-1/2"" Diameter Ridgewood Wall ...",155.8200,3.0,0.0,467.4600,109.07400,327.22200,140.23800,4,30.0
1005,CA-2015-108665,2015,Jul,2015-07-06,2015-07-10,Standard Class,KM-16225,Kalyca Meade,Corporate,United States,...,OtterBox Commuter Series Case - Samsung Galaxy S4,124.9500,5.0,0.0,624.7500,87.46500,437.32500,187.42500,4,30.0

In [72]:
df.to_excel(r'D:\Data Analytics\sales_analysis\dataset\sales_clean_data.xlsx' , sheet_name='Sales Data' , index=False)