# python data cleaning of sales analysis

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel(r'D:\Data Analytics\sales_analysis\dataset\Sales_Data.xlsx' , sheet_name='Sales Data')
df.head(5)

,Order ID,Year,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Client Segment,Country,...,Product Category,Sub-Category,Product Name,Sales Price,Quantity,Discount,Total Sales Amount,Purchasing Price,Total Purchasing Amounts,Net Profit
0,CA-2016-152156,2020.0,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.0,523.9200,157.17600,314.35200,209.56800
1,CA-2016-152156,2020.0,Nov,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.0,2195.8200,402.56700,1207.70100,988.11900
2,CA-2016-138688,2020.0,Jun,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.0,29.2400,8.77200,17.54400,11.69600
3,US-2015-108966,2020.0,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.0,4787.8875,478.78875,2393.94375,2393.94375
4,US-2015-108966,2020.0,Oct,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.0,35.7888,11.18400,22.36800,13.42080

In [8]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ' , '_')
df.columns

Index(['order_id', 'year', 'month', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'client_segment', 'country', 'state',
       'postal_code', 'region', 'product_id', 'product_category',
       'sub-category', 'product_name', 'sales_price', 'quantity', 'discount',
       'total_sales_amount', 'purchasing_price', 'total_purchasing_amounts',
       'net_profit'],
      dtype='object')

In [15]:
df.info()
print('=='*20)
print('null check')
print('=='*20)
print(df.isnull().sum())
print('=='*20)
print('duplicate check')
print('=='*20)
print(df.duplicated().sum())
print('=='*20)
print('data shape before cleaning')
print('=='*20)
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   order_id                  1013 non-null   object
 1   year                      1013 non-null   float64
 2   month                     1013 non-null   object
 3   order_date                1011 non-null   datetime64[ns]
 4   ship_date                 1013 non-null   datetime64[ns]
 5   ship_mode                 1008 non-null   object
 6   customer_id               1013 non-null   object
 7   customer_name             1009 non-null   object
 8   client_segment            1013 non-null   object
 9   country                   1013 non-null   object
 10  state                     1013 non-null   object
 11  postal_code               1010 non-null   float64
 12  region                    1013 non-null   object
 13  product_id                1013 non-null   object
 14  product_category          1010 non-null   object
 15  sub-category              1013 non-null   object
 16  product_name              1013 non-null   object
 17  sales_price               1005 non-null   float64
 18  quantity                  1013 non-null   float64
 19  discount                  1013 non-null   float64
 20  total_sales_amount        1013 non-null   float64
 21  purchasing_price          1013 non-null   float64
 22  total_purchasing_amounts  1013 non-null   float64
 23  net_profit                1013 non-null   float64
dtypes: datetime64[ns](2), float64(9), object(13)
memory usage: 190.3+ KB
========================================
null check
========================================
order_id                    1
year                        1
month                       1
order_date                  3
ship_date                   1
ship_mode                   6
customer_id                 1
customer_name               5
client_segment              1
country                     1
state                       1
postal_code                 4
region                      1
product_id                  1
product_category            4
sub-category                1
product_name                1
sales_price                 9
quantity                    1
discount                    1
total_sales_amount          1
purchasing_price            1
total_purchasing_amounts    1
net_profit                  1
dtype: int64
========================================
duplicate check
========================================
7
========================================
data shape before cleaning
========================================
(1014, 24)

In [ ]:
# sort missing 
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

sales_price                 9
ship_mode                   6
customer_name               5
postal_code                 4
product_category            4
order_date                  3
month                       1
order_id                    1
customer_id                 1
ship_date                   1
year                        1
country                     1
state                       1
region                      1
product_id                  1
client_segment              1
sub-category                1
product_name                1
quantity                    1
discount                    1
total_sales_amount          1
purchasing_price            1
total_purchasing_amounts    1
net_profit                  1
dtype: int64

* to check fully missing row

In [16]:
df[df.isnull().all(axis=1)]

,order_id,year,month,order_date,ship_date,ship_mode,customer_id,customer_name,client_segment,country,...,product_category,sub-category,product_name,sales_price,quantity,discount,total_sales_amount,purchasing_price,total_purchasing_amounts,net_profit
648,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

* remove this full miss row

In [18]:
df = df.dropna(how='all').reset_index(drop=True)
print('data shape after remove full miss row')
df.shape

data shape after remove full miss row

(1013, 24)

* to check which row exact duplicate

In [20]:
# Display all rows involved in duplication
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,order_id,year,month,order_date,ship_date,ship_mode,customer_id,customer_name,client_segment,country,...,product_category,sub-category,product_name,sales_price,quantity,discount,total_sales_amount,purchasing_price,total_purchasing_amounts,net_profit
40,CA-2017-120999,2017.0,Sep,2017-09-10,2017-09-15,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,...,Technology,Phones,Panasonic Kx-TS550,147.168,4.0,0.0,470.9376,80.9424,323.7696,147.1680
179,CA-2014-158274,2014.0,Nov,2014-11-19,2014-11-24,Second Class,RM-19675,Robert Marley,Home Office,United States,...,Technology,Phones,Nokia Lumia 521 (T-Mobile),149.950,5.0,0.0,749.7500,74.9750,374.8750,374.8750
354,CA-2017-155698,2017.0,Mar,2017-03-08,2017-03-11,First Class,VB-21745,Victoria Brennan,Corporate,United States,...,Office Supplies,Appliances,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,647.840,8.0,0.0,5182.7200,421.0960,3368.7680,1813.9520
507,CA-2017-127432,2017.0,Jan,2017-01-22,2017-01-27,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,...,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,11.960,2.0,0.0,23.9200,8.3720,16.7440,7.1760
705,CA-2014-104472,2014.0,Jun,2014-06-02,2014-06-07,Standard Class,CK-12325,Christine Kargatis,Home Office,United States,...,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,59.808,3.0,0.0,143.5392,41.8656,125.5968,17.9424
872,CA-2015-143602,2015.0,Apr,2015-04-25,2015-04-28,Second Class,JS-15595,Jill Stevenson,Corporate,United States,...,Office Supplies,Binders,Fellowes Black Plastic Comb Bindings,13.944,3.0,0.0,33.4656,9.0636,27.1908,6.2748
997,CA-2014-158540,2014.0,Nov,2014-11-24,2014-11-26,First Class,VG-21790,Vivek Gonzalez,Consumer,United States,...,Furniture,Furnishings,"Eldon Delta Triangular Chair Mat, 52"" x 58"", C...",151.720,4.0,0.0,606.8800,91.0320,364.1280,242.7520
1006,CA-2017-120999,2017.0,Sep,2017-09-10,2017-09-15,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,...,Technology,Phones,Panasonic Kx-TS550,147.168,4.0,0.0,470.9376,80.9424,323.7696,147.1680
1007,CA-2014-158274,2014.0,Nov,2014-11-19,2014-11-24,Second Class,RM-19675,Robert Marley,Home Office,United States,...,Technology,Phones,Nokia Lumia 521 (T-Mobile),149.950,5.0,0.0,749.7500,74.9750,374.8750,374.8750
1008,CA-2017-155698,2017.0,Mar,2017-03-08,2017-03-11,First Class,VB-21745,Victoria Brennan,Corporate,United States,...,Office Supplies,Appliances,Belkin 8 Outlet SurgeMaster II Gold Surge Prot...,647.840,8.0,0.0,5182.7200,421.0960,3368.7680,1813.9520
1009,CA-2017-127432,2017.0,Jan,2017-01-22,2017-01-27,Standard Class,AD-10180,Alan Dominguez,Home Office,United States,...,Office Supplies,Paper,Great White Multi-Use Recycled Paper (20Lb. an...,11.960,2.0,0.0,23.9200,8.3720,16.7440,7.1760
1010,CA-2014-104472,2014.0,Jun,2014-06-02,2014-06-07,Standard Class,CK-12325,Christine Kargatis,Home Office,United States,...,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,59.808,3.0,0.0,143.5392,41.8656,125.5968,17.9424
1011,CA-2015-143602,2015.0,Apr,2015-04-25,2015-04-28,Second Class,JS-15595,Jill Stevenson,Corporate,United States,...,Office Supplies,Binders,Fellowes Black Plastic Comb Bindings,13.944,3.0,0.0,33.4656,9.0636,27.1908,6.2748
1012,CA-2014-158540,2014.0,Nov,2014-11-24,2014-11-26,First Class,VG-21790,Vivek Gonzalez,Consumer,United States,...,Furniture,Furnishings,"Eldon Delta Triangular Chair Mat, 52"" x 58"", C...",151.720,4.0,0.0,606.8800,91.0320,364.1280,242.7520

* drop duplicate rows

In [ ]:
# 1014 - 1 - 7
df = df.drop_duplicates().reset_index(drop=True)
print('after remove duplicate data shape')
df.shape

after remove duplicate data shape

(1006, 24)

* customer fill

In [39]:
name_lookup = df.dropna(subset=['customer_name']).drop_duplicates('customer_id').set_index('customer_id')['customer_name']

df['customer_name'] = df['customer_name'].fillna(df['customer_id'].map(name_lookup))

df['customer_name'] = df['customer_name'].fillna('Unknown Customer')

# after fill check missing
customer_missing = df['customer_name'].isnull().sum()
if customer_missing > 0:
    print(f'There are still {customer_missing} missing customer names.')    
else:
    print('All missing customer names have been filled.')

All missing customer names have been filled.

All missing customer names have been filled.

In [38]:
df.shape

(1006, 24)