In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\Data Analytics\DA_python_projects\netflix_analysis\dataset\Netflix Dataset.csv')
df.head(5)

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
df.columns

Index(['show_id', 'category', 'title', 'director', 'cast', 'country',
       'release_date', 'rating', 'duration', 'type', 'description'],
      dtype='object')

In [4]:
df.info()
print("--"* 20)
print(f"null chheck : \n{df.isnull().sum()/ len(df)*100}")
print("--"* 20)
print(f"duplicate check : \n{df.duplicated().sum()}")
print("--"* 20)
print(f" data shape before clean: {df.shape}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7789 non-null   object
 1   category      7789 non-null   object
 2   title         7789 non-null   object
 3   director      5401 non-null   object
 4   cast          7071 non-null   object
 5   country       7282 non-null   object
 6   release_date  7779 non-null   object
 7   rating        7782 non-null   object
 8   duration      7789 non-null   object
 9   type          7789 non-null   object
 10  description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB
----------------------------------------
null chheck :
show_id          0.000000
category         0.000000
title            0.000000
director        30.658621
cast             9.218128
country          6.509180
release_date     0.128386
rating           0.089870
duration         0.000000
type             0.000000
description      0.000000
dtype: float64
----------------------------------------
duplicate check :
2
----------------------------------------
 data shape before clean: (7789, 11)

In [5]:
df['show_id'].duplicated().any()

np.True_

**here show id have duplicate that means show id is not primary key**

In [6]:
# Display all rows involved in duplication
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,show_id,category,title,director,cast,country,release_date,rating,duration,type,description
683,s684,Movie,Backfire,Dave Patten,"Black Deniro, Byron ""Squally"" Vinson, Dominic ...",United States,"April 5, 2019",TV-MA,97 min,"Dramas, Independent Movies, Thrillers",When two would-be robbers accidentally kill a ...
4839,s6621,Movie,The Lost Okoroshi,Abba T. Makama,"Seun Ajayi, Judith Audu, Tope Tedela, Ifu Enna...",Nigeria,"September 4, 2020",TV-MA,94 min,"Comedies, Dramas, Independent Movies",A disillusioned security guard transforms into...
6300,s684,Movie,Backfire,Dave Patten,"Black Deniro, Byron ""Squally"" Vinson, Dominic ...",United States,"April 5, 2019",TV-MA,97 min,"Dramas, Independent Movies, Thrillers",When two would-be robbers accidentally kill a ...
6622,s6621,Movie,The Lost Okoroshi,Abba T. Makama,"Seun Ajayi, Judith Audu, Tope Tedela, Ifu Enna...",Nigeria,"September 4, 2020",TV-MA,94 min,"Comedies, Dramas, Independent Movies",A disillusioned security guard transforms into...

* drop duplicate

In [7]:
df = df.drop_duplicates().reset_index(drop=True)
print('after remove duplicate data shape')
df.shape

after remove duplicate data shape

(7787, 11)

* handle missing value

In [8]:
df[['director', 'cast', 'country']] = df[['director', 'cast', 'country']].fillna('Unknown')

df[['rating']] = df[['rating']].fillna('Not Rated')

print('after handle null value')
print(df.isnull().sum())

after handle null value
show_id          0
category         0
title            0
director         0
cast             0
country          0
release_date    10
rating           0
duration         0
type             0
description      0
dtype: int64

In [9]:
df = df.rename(columns={'release_date': 'date_added', 'type': 'genres'})

In [10]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce', format='mixed')
df = df.dropna(subset=['date_added'])
print('after handle null value')
print(df.isnull().sum())

after handle null value
show_id        0
category       0
title          0
director       0
cast           0
country        0
date_added     0
rating         0
duration       0
genres         0
description    0
dtype: int64

In [11]:
# remove white space from object 
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

In [13]:
df = df.drop(columns=['description'])

In [14]:
# check unique values
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    vals = df[col].unique()
    print(f"\n{col} ({len(vals)} unique): {sorted(vals)}")

show_id (7777 unique): ['s1', 's10', 's100', 's1000', 's1001', 's1002', 's1003', 's1004', 's1005', 's1006', 's1007', 's1008', 's1009', 's101', 's1010', 's1011', 's1012', 's1013', 's1014', 's1015', 's1016', 's1017', 's1018', 's1019', 's102', 's1020', 's1021', 's1022', 's1023', 's1024', 's1025', 's1026', 's1027', 's1028', 's1029', 's103', 's1030', 's1031', 's1032', 's1033', 's1034', 's1035', 's1036', 's1037', 's1038', 's1039', 's104', 's1040', 's1041', 's1042', 's1043', 's1044', 's1045', 's1046', 's1047', 's1048', 's1049', 's105', 's1050', 's1051', 's1052', 's1053', 's1054', 's1055', 's1056', 's1057', 's1058', 's1059', 's106', 's1060', 's1061', 's1062', 's1063', 's1064', 's1065', 's1066', 's1067', 's1068', 's1069', 's107', 's1070', 's1071', 's1072', 's1073', 's1074', 's1075', 's1076', 's1077', 's1078', 's1079', 's108', 's1080', 's1081', 's1082', 's1083', 's1084', 's1085', 's1086', 's1087', 's1088', 's1089', 's109', 's1090', 's1091', 's1092', 's1093', 's1094', 's1095', 's1096', 's1097', 's1098', 's1099', 's11', 's110', 's1100', 's1101', 's1102', 's1103', 's1104', 's1105', 's1106', 's1107', 's1108', 's1109', 's111', 's1110', 's1111', 's1112', 's1113', 's1114', 's1115', 's1116', 's1117', 's1118', 's1119', 's112', 's1120', 's1121', 's1122', 's1123', 's1124', 's1125', 's1126', 's1127', 's1128', 's1129', 's113', 's1130', 's1131', 's1132', 's1133', 's1134', 's1135', 's1136', 's1137', 's1138', 's1139', 's114', 's1140', 's1141', 's1142', 's1143', 's1144', 's1145', 's1146', 's1147', 's1148', 's1149', 's115', 's1150', 's1151', 's1152', 's1153', 's1154', 's1155', 's1156', 's1157', 's1158', 's1159', 's116', 's1160', 's1161', 's1162', 's1163', 's1164', 's1165', 's1166', 's1167', 's1168', 's1169', 's117', 's1170', 's1171', 's1172', 's1173', 's1174', 's1175', 's1176', 's1177', 's1178', 's1179', 's118', 's1180', 's1181', 's1182', 's1183', 's1184', 's1185', 's1186', 's1187', 's1188', 's1189', 's119', 's1190', 's1191', 's1192', 's1193', 's1194', 's1195', 's1196', 's1197', 's1198', 's1199', 's12', 's120', 's1200', 's1201', 's1202', 's1203', 's1204', 's1205', 's1206', 's1207', 's1208', 's1209', 's121', 's1210', 's1211', 's1212', 's1213', 's1214', 's1215', 's1216', 's1217', 's1218', 's1219', 's122', 's1220', 's1221', 's1222', 's1223', 's1224', 's1225', 's1226', 's1227', 's1228', 's1229', 's123', 's1230', 's1231', 's1232', 's1233', 's1234', 's1235', 's1236', 's1237', 's1238', 's1239', 's124', 's1240', 's1241', 's1242', 's1243', 's1244', 's1245', 's1246', 's1247', 's1248', 's1249', 's125', 's1250', 's1251', 's1252', 's1253', 's1254', 's1255', 's1256', 's1257', 's1258', 's1259', 's126', 's1260', 's1261', 's1262', 's1263', 's1264', 's1265', 's1266', 's1267', 's1268', 's1269', 's127', 's1270', 's1271', 's1272', 's1273', 's1274', 's1275', 's1276', 's1277', 's1278', 's1279', 's128', 's1280', 's1281', 's1282', 's1283', 's1284', 's1285', 's1286', 's1287', 's1288', 's1289', 's129', 's1290', 's1291', 's1292', 's1293', 's1294', 's1295', 's1296', 's1297', 's1298', 's1299', 's13', 's130', 's1300', 's1301', 's1302', 's1303', 's1304', 's1305', 's1306', 's1307', 's1308', 's1309', 's131', 's1310', 's1311', 's1312', 's1313', 's1314', 's1315', 's1316', 's1317', 's1318', 's1319', 's132', 's1320', 's1321', 's1322', 's1323', 's1324', 's1325', 's1326', 's1327', 's1328', 's1329', 's133', 's1330', 's1331', 's1332', 's1333', 's1334', 's1335', 's1336', 's1337', 's1338', 's1339', 's134', 's1340', 's1341', 's1342', 's1343', 's1344', 's1345', 's1346', 's1347', 's1348', 's1349', 's135', 's1350', 's1351', 's1352', 's1353', 's1354', 's1355', 's1356', 's1357', 's1358', 's1359', 's136', 's1360', 's1361', 's1362', 's1363', 's1364', 's1365', 's1366', 's1367', 's1368', 's1369', 's137', 's1370', 's1371', 's1372', 's1373', 's1374', 's1375', 's1376', 's1377', 's1378', 's1379', 's138', 's1380', 's1381', 's1382', 's1383', 's1384', 's1385', 's1386', 's1387', 's1388', 's1389', 's139', 's1390', 's1391', 's1392', 's1393', 's1394', 's1395', 's1396', 's1397', 's1398', 's1399', 's14', 's140', 's1400', 's1401', 's1402', 's1403', 's1404', 's1405', 's1406', 's1407', 's1408', 's1409', 's141', 's1410', 's1411', 's1412', 's1413', 's1414', 's1415', 's1416', 's1417', 's1418', 's1419', 's142', 's1420', 's1421', 's1422', 's1423', 's1424', 's1425', 's1426', 's1427', 's1428', 's1429', 's143', 's1430', 's1431', 's1432', 's1433', 's1434', 's1435', 's1436', 's1437', 's1438', 's1439', 's144', 's1440', 's1441', 's1442', 's1443', 's1444', 's1445', 's1446', 's1447', 's1448', 's1449', 's145', 's1450', 's1451', 's1452', 's1453', 's1454', 's1455', 's1456', 's1457', 's1458', 's1459', 's146', 's1460', 's1461', 's1462', 's1463', 's1464', 's1465', 's1466', 's1467', 's1468', 's1469', 's147', 's1470', 's1471', 's1472', 's1473', 's1474', 's1475', 's1476', 's1477', 's1478', 's1479', 's148', 's1480', 's1481', 's1482', 's1483', 's1484', 's1485', 's1486', 's1487', 's1488', 's1489', 's149', 's1490', 's1491', 's1492', 's1493', 's1494', 's1495', 's1496', 's1497', 's1498', 's1499', 's15', 's150', 's1500', 's1501', 's1502', 's1503', 's1504', 's1505', 's1506', 's1507', 's1508', 's1509', 's151', 's1510', 's1511', 's1512', 's1513', 's1514', 's1515', 's1516', 's1517', 's1518', 's1519', 's152', 's1520', 's1521', 's1522', 's1523', 's1524', 's1525', 's1526', 's1527', 's1528', 's1529', 's153', 's1530', 's1531', 's1532', 's1533', 's1534', 's1535', 's1536', 's1537', 's1538', 's1539', 's154', 's1540', 's1541', 's1542', 's1543', 's1544', 's1545', 's1546', 's1547', 's1548', 's1549', 's155', 's1550', 's1551', 's1552', 's1553', 's1554', 's1555', 's1556', 's1557', 's1558', 's1559', 's156', 's1560', 's1561', 's1562', 's1563', 's1564', 's1565', 's1566', 's1567', 's1568', 's1569', 's157', 's1570', 's1571', 's1572', 's1573', 's1574', 's1575', 's1576', 's1577', 's1578', 's1579', 's158', 's1580', 's1581', 's1582', 's1583', 's1584', 's1585', 's1586', 's1587', 's1588', 's1589', 's159', 's1590', 's1591', 's1592', 's1593', 's1594', 's1595', 's1596', 's1597', 's1598', 's1599', 's16', 's160', 's1600', 's1601', 's1602', 's1603', 's1604', 's1605', 's1606', 's1607', 's1608', 's1609', 's161', 's1610', 's1611', 's1612', 's1613', 's1614', 's1615', 's1616', 's1617', 's1618', 's1619', 's162', 's1620', 's1621', 's1622', 's1623', 's1624', 's1625', 's1626', 's1627', 's1628', 's1629', 's163', 's1630', 's1631', 's1632', 's1633', 's1634', 's1635', 's1636', 's1637', 's1638', 's1639', 's164', 's1640', 's1641', 's1642', 's1643', 's1644', 's1645', 's1646', 's1647', 's1648', 's1649', 's165', 's1650', 's1651', 's1652', 's1653', 's1654', 's1655', 's1656', 's1657', 's1658', 's1659', 's166', 's1660', 's1661', 's1662', 's1663', 's1664', 's1665', 's1666', 's1667', 's1668', 's1669', 's167', 's1670', 's1671', 's1672', 's1673', 's1674', 's1675', 's1676', 's1677', 's1678', 's1679', 's168', 's1680', 's1681', 's1682', 's1683', 's1684', 's1685', 's1686', 's1687', 's1688', 's1689', 's169', 's1690', 's1691', 's1692', 's1693', 's1694', 's1695', 's1696', 's1697', 's1698', 's1699', 's17', 's170', 's1700', 's1701', 's1702', 's1703', 's1704', 's1705', 's1706', 's1707', 's1708', 's1709', 's171', 's1710', 's1711', 's1712', 's1713', 's1714', 's1715', 's1716', 's1717', 's1718', 's1719', 's172', 's1720', 's1721', 's1722', 's1723', 's1724', 's1725', 's1726', 's1727', 's1728', 's1729', 's173', 's1730', 's1731', 's1732', 's1733', 's1734', 's1735', 's1736', 's1737', 's1738', 's1739', 's174', 's1740', 's1741', 's1742', 's1743', 's1744', 's1745', 's1746', 's1747', 's1748', 's1749', 's175', 's1750', 's1751', 's1752', 's1753', 's1754', 's1755', 's1756', 's1757', 's1758', 's1759', 's176', 's1760', 's1761', 's1762', 's1763', 's1764', 's1765', 's1766', 's1767', 's1768', 's1769', 's177', 's1770', 's1771', 's1772', 's1773', 's1774', 's1775', 's1776', 's1777', 's1778', 's1779', 's178', 's1780', 's1781', 's1782', 's1783', 's1784', 's1785', 's1786', 's1787', 's1788', 's1789', 's179', 's1790', 's1791', 's1792', 's1793', 's1794', 's1795', 's1796', 's1797', 's1798', 's1799', 's18', 's180', 's1800', 's1801', 's1802', 's1803', 's1804', 's1805', 's1806', 's1807', 's1808', 's1809', 's181', 's1810', 's1811', 's1812', 's1813', 's1814', 's1815', 's1816', 's1817', 's1818', 's1819', 's182', 's1820', 's1821', 's1822', 's1823', 's1824', 's1825', 's1826', 's1827', 's1828', 's1829', 's183', 's1830', 's1831', 's1832', 's1833', 's1834', 's1835', 's1836', 's1837', 's1838', 's1839', 's184', 's1840', 's1841', 's1842', 's1843', 's1844', 's1845', 's1846', 's1847', 's1848', 's1849', 's185', 's1850', 's1851', 's1852', 's1853', 's1854', 's1855', 's1856', 's1857', 's1858', 's1859', 's186', 's1860', 's1861', 's1862', 's1863', 's1864', 's1865', 's1866', 's1867', 's1868', 's1869', 's187', 's1870', 's1871', 's1872', 's1873', 's1874', 's1875', 's1876', 's1877', 's1878', 's1879', 's188', 's1880', 's1881', 's1882', 's1883', 's1884', 's1885', 's1886', 's1887', 's1888', 's1889', 's189', 's1890', 's1891', 's1892', 's1893', 's1894', 's1895', 's1896', 's1897', 's1898', 's1899', 's19', 's190', 's1900', 's1901', 's1902', 's1903', 's1904', 's1905', 's1906', 's1907', 's1908', 's1909', 's191', 's1910', 's1911', 's1912', 's1913', 's1914', 's1915', 's1916', 's1917', 's1918', 's1919', 's192', 's1920', 's1921', 's1922', 's1923', 's1924', 's1925', 's1926', 's1927', 's1928', 's1929', 's193', 's1930', 's1931', 's1932', 's1933', 's1934', 's1935', 's1936', 's1937', 's1938', 's1939', 's194', 's1940', 's1941', 's1942', 's1943', 's1944', 's1945', 's1946', 's1947', 's1948', 's1949', 's195', 's1950', 's1951', 's1952', 's1953', 's1954', 's1955', 's1956', 's1957', 's1958', 's1959', 's196', 's1960', 's1961', 's1962', 's1963', 's1964', 's1965', 's1966', 's1967', 's1968', 's1969', 's197', 's1970', 's1971', 's1972', 's1973', 's1974', 's1975', 's1976', 's1977', 's1978', 's1979', 's198', 's1980', 's1981', 's1982', 's1983', 's1984', 's1985', 's1986', 's1987', 's1988', 's1989', 's199', 's1990', 's1991', 's1992', 's1993', 's1994', 's1995', 's1996', 's1997', 's1998', 's1999', 's2', 's20', 's200', 's2000', 's2001', 's2002', 's2003', 's2004', 's2005', 's2006', 's2007', 's2008', 's2009', 's201', 's2010', 's2011', 's2012', 's2013', 's2014', 's2015', 's2016', 's2017', 's2018', 's2019', 's202', 's2020', 's2021', 's2022', 's2023', 's2024', 's2025', 's2026', 's2027', 's2028', 's2029', 's203', 's2030', 's2031', 's2032', 's2033', 's2034', 's2035', 's2036', 's2037', 's2038', 's2039', 's204', 's2040', 's2041', 's2042', 's2043', 's2044', 's2045', 's2046', 's2047', 's2048', 's2049', 's205', 's2050', 's2051', 's2052', 's2053', 's2054', 's2055', 's2056', 's2057', 's2058', 's2059', 's206', 's2060', 's2061', 's2062', 's2063', 's2064', 's2065', 's2066', 's2067', 's2068', 's2069', 's207', 's2070', 's2071', 's2072', 's2073', 's2074', 's2075', 's2076', 's2077', 's2078', 's2079', 's208', 's2080', 's2081', 's2082', 's2083', 's2084', 's2085', 's2086', 's2087', 's2088', 's2089', 's209', 's2090', 's2091', 's2092', 's2093', 's2094', 's2095', 's2096', 's2097', 's2098', 's2099', 's21', 's210', 's2100', 's2101', 's2102', 's2103', 's2104', 's2105', 's2106', 's2107', 's2108', 's2109', 's211', 's2110', 's2111', 's2112', 's2113', 's2114', 's2115', 's2116', 's2117', 's2118', 's2119', 's212', 's2120', 's2121', 's2122', 's2123', 's2124', 's2125', 's2126', 's2127', 's2128', 's2129', 's213', 's2130', 's2131', 's2132', 's2133', 's2134', 's2135', 's2136', 's2137', 's2138', 's2139', 's214', 's2140', 's2141', 's2142', 's2143', 's2144', 's2145', 's2146', 's2147', 's2148', 's2149', 's215', 's2150', 's2151', 's2152', 's2153', 's2154', 's2155', 's2156', 's2157', 's2158', 's2159', 's216', 's2160', 's2161', 's2162', 's2163', 's2164', 's2165', 's2166', 's2167', 's2168', 's2169', 's217', 's2170', 's2171', 's2172', 's2173', 's2174', 's2175', 's2176', 's2177', 's2178', 's2179', 's218', 's2180', 's2181', 's2182', 's2183', 's2184', 's2185', 's2186', 's2187', 's2188', 's2189', 's219', 's2190', 's2191', 's2192', 's2193', 's2194', 's2195', 's2196', 's2197', 's2198', 's2199', 's22', 's220', 's2200', 's2201', 's2202', 's2203', 's2204', 's2205', 's2206', 's2207', 's2208', 's2209', 's221', 's2210', 's2211', 's2212', 's2213', 's2214', 's2215', 's2216', 's2217', 's2218', 's2219', 's222', 's2220', 's2221', 's2222', 's2223', 's2224', 's2225', 's2226', 's2227', 's2228', 's2229', 's223', 's2230', 's2231', 's2232', 's2233', 's2234', 's2235', 's2236', 's2237', 's2238', 's2239', 's224', 's2240', 's2241', 's2242', 's2243', 's2244', 's2245', 's2246', 's2247', 's2248', 's2249', 's225', 's2250', 's2251', 's2252', 's2253', 's2254', 's2255', 's2256', 's2257', 's2258', 's2259', 's226', 's2260', 's2261', 's2262', 's2263', 's2265', 's2266', 's2267', 's2268', 's2269', 's227', 's2270', 's2271', 's2272', 's2273', 's2274', 's2275', 's2276', 's2277', 's2278', 's2279', 's228', 's2280', 's2281', 's2282', 's2283', 's2284', 's2285', 's2286', 's2287', 's2288', 's229', 's2290', 's2291', 's2292', 's2293', 's2294', 's2295', 's2296', 's2297', 's2298', 's2299', 's23', 's230', 's2300', 's2301', 's2302', 's2303', 's2304', 's2305', 's2306', 's2307', 's2308', 's2309', 's231', 's2310', 's2311', 's2312', 's2313', 's2314', 's2315', 's2316', 's2317', 's2318', 's2319', 's232', 's2320', 's2321', 's2322', 's2323', 's2324', 's2325', 's2326', 's2327', 's2328', 's2329', 's233', 's2330', 's2331', 's2332', 's2333', 's2334', 's2335', 's2336', 's2337', 's2338', 's2339', 's234', 's2340', 's2341', 's2342', 's2343', 's2344', 's2345', 's2346', 's2347', 's2348', 's2349', 's235', 's2350', 's2351', 's2352', 's2353', 's2354', 's2355', 's2356', 's2357', 's2358', 's2359', 's236', 's2360', 's2361', 's2362', 's2363', 's2364', 's2365', 's2366', 's2367', 's2368', 's2369', 's237', 's2370', 's2371', 's2372', 's2373', 's2374', 's2375', 's2376', 's2377', 's2378', 's2379', 's238', 's2380', 's2381', 's2382', 's2383', 's2384', 's2385', 's2386', 's2387', 's2388', 's2389', 's239', 's2390', 's2391', 's2392', 's2393', 's2394', 's2395', 's2396', 's2397', 's2398', 's2399', 's24', 's240', 's2400', 's2401', 's2402', 's2403', 's2404', 's2405', 's2406', 's2407', 's2408', 's2409', 's241', 's2410', 's2411', 's2412', 's2413', 's2414', 's2415', 's2416', 's2417', 's2418', 's2419', 's242', 's2420', 's2421', 's2422', 's2423', 's2424', 's2425', 's2426', 's2427', 's2428', 's2429', 's243', 's2430', 's2431', 's2432', 's2433', 's2434', 's2435', 's2436', 's2437', 's2438', 's2439', 's244', 's2440', 's2441', 's2442', 's2443', 's2444', 's2445', 's2446', 's2447', 's2448', 's2449', 's245', 's2450', 's2451', 's2452', 's2453', 's2454', 's2455', 's2456', 's2457', 's2458', 's2459', 's246', 's2460', 's2461', 's2462', 's2463', 's2464', 's2465', 's2466', 's2467', 's2468', 's2469', 's247', 's2470', 's2471', 's2472', 's2473', 's2474', 's2475', 's2476', 's2477', 's2478', 's2479', 's248', 's2480', 's2481', 's2482', 's2483', 's2484', 's2485', 's2486', 's2487', 's2488', 's2489', 's249', 's2490', 's2491', 's2492', 's2493', 's2494', 's2495', 's2496', 's2497', 's2498', 's2499', 's25', 's250', 's2500', 's2501', 's2502', 's2503', 's2504', 's2505', 's2506', 's2507', 's2508', 's2509', 's251', 's2510', 's2511', 's2512', 's2513', 's2514', 's2515', 's2516', 's2517', 's2518', 's2519', 's252', 's2520', 's2521', 's2522', 's2523', 's2524', 's2525', 's2526', 's2527', 's2528', 's2529', 's253', 's2530', 's2531', 's2532', 's2533', 's2534', 's2535', 's2536', 's2537', 's2538', 's2539', 's254', 's2540', 's2541', 's2542', 's2543', 's2544', 's2545', 's2546', 's2547', 's2548', 's2549', 's255', 's2550', 's2551', 's2552', 's2553', 's2554', 's2555', 's2557', 's2558', 's2559', 's256', 's2560', 's2561', 's2562', 's2563', 's2564', 's2565', 's2566', 's2567', 's2568', 's2569', 's257', 's2570', 's2571', 's2572', 's2573', 's2574', 's2575', 's2576', 's2577', 's2578', 's2579', 's258', 's2580', 's2581', 's2582', 's2583', 's2584', 's2585', 's2586', 's2587', 's2588', 's2589', 's2590', 's2591', 's2592', 's2593', 's2594', 's2595', 's2596', 's2597', 's2598', 's2599', 's26', 's260', 's2600', 's2601', 's2602', 's2603', 's2604', 's2605', 's2606', 's2607', 's2608', 's2609', 's261', 's2610', 's2611', 's2612', 's2613', 's2614', 's2615', 's2616', 's2617', 's2618', 's2619', 's262', 's2620', 's2621', 's2622', 's2623', 's2624', 's2625', 's2626', 's2627', 's2628', 's2629', 's263', 's2630', 's2631', 's2632', 's2633', 's2634', 's2635', 's2636', 's2637', 's2638', 's2639', 's264', 's2640', 's2641', 's2642', 's2643', 's2644', 's2645', 's2646', 's2647', 's2648', 's2649', 's265', 's2650', 's2651', 's2652', 's2653', 's2654', 's2655', 's2656', 's2657', 's2658', 's2659', 's266', 's2660', 's2661', 's2662', 's2663', 's2664', 's2665', 's2666', 's2667', 's2668', 's2669', 's267', 's2670', 's2671', 's2672', 's2673', 's2674', 's2675', 's2676', 's2677', 's2678', 's2679', 's268', 's2680', 's2681', 's2682', 's2683', 's2684', 's2685', 's2686', 's2687', 's2688', 's2689', 's269', 's2690', 's2691', 's2692', 's2693', 's2694', 's2695', 's2696', 's2697', 's2698', 's2699', 's27', 's270', 's2700', 's2701', 's2702', 's2703', 's2704', 's2705', 's2706', 's2707', 's2708', 's2709', 's271', 's2710', 's2711', 's2712', 's2713', 's2714', 's2715', 's2716', 's2717', 's2718', 's2719', 's272', 's2720', 's2721', 's2722', 's2723', 's2724', 's2725', 's2726', 's2727', 's2728', 's2729', 's273', 's2730', 's2731', 's2732', 's2733', 's2734', 's2735', 's2736', 's2737', 's2738', 's2739', 's274', 's2740', 's2741', 's2742', 's2743', 's2744', 's2745', 's2746', 's2747', 's2748', 's2749', 's275', 's2750', 's2751', 's2752', 's2753', 's2754', 's2755', 's2756', 's2757', 's2758', 's2759', 's276', 's2760', 's2761', 's2762', 's2763', 's2764', 's2765', 's2766', 's2767', 's2768', 's2769', 's277', 's2770', 's2771', 's2772', 's2773', 's2774', 's2775', 's2776', 's2777', 's2778', 's2779', 's278', 's2780', 's2781', 's2782', 's2783', 's2784', 's2785', 's2786', 's2787', 's2788', 's2789', 's279', 's2790', 's2791', 's2792', 's2793', 's2794', 's2795', 's2796', 's2797', 's2798', 's2799', 's28', 's280', 's2800', 's2801', 's2802', 's2803', 's2804', 's2805', 's2806', 's2807', 's2808', 's2809', 's281', 's2810', 's2811', 's2812', 's2813', 's2814', 's2815', 's2816', 's2817', 's2818', 's2819', 's282', 's2820', 's2821', 's2822', 's2823', 's2824', 's2825', 's2826', 's2827', 's2828', 's2829', 's283', 's2830', 's2831', 's2832', 's2833', 's2834', 's2835', 's2836', 's2837', 's2838', 's2839', 's284', 's2840', 's2841', 's2842', 's2843', 's2844', 's2845', 's2846', 's2847', 's2848', 's2849', 's285', 's2850', 's2851', 's2852', 's2853', 's2854', 's2855', 's2856', 's2857', 's2858', 's2859', 's286', 's2860', 's2861', 's2862', 's2863', 's2864', 's2865', 's2866', 's2867', 's2868', 's2869', 's287', 's2870', 's2871', 's2872', 's2873', 's2874', 's2875', 's2876', 's2877', 's2878', 's2879', 's288', 's2880', 's2881', 's2882', 's2883', 's2884', 's2885', 's2886', 's2887', 's2888', 's2889', 's289', 's2890', 's2891', 's2892', 's2893', 's2894', 's2895', 's2896', 's2897', 's2898', 's2899', 's29', 's290', 's2900', 's2901', 's2902', 's2903', 's2904', 's2905', 's2906', 's2907', 's2908', 's2909', 's291', 's2910', 's2911', 's2912', 's2913', 's2914', 's2915', 's2916', 's2917', 's2918', 's2919', 's292', 's2920', 's2921', 's2922', 's2923', 's2924', 's2925', 's2926', 's2927', 's2928', 's2929', 's293', 's2930', 's2931', 's2932', 's2933', 's2934', 's2935', 's2936', 's2937', 's2938', 's2939', 's294', 's2940', 's2941', 's2942', 's2943', 's2944', 's2945', 's2946', 's2947', 's2948', 's2949', 's295', 's2950', 's2951', 's2952', 's2953', 's2954', 's2955', 's2956', 's2957', 's2958', 's2959', 's296', 's2960', 's2961', 's2962', 's2963', 's2964', 's2965', 's2966', 's2967', 's2968', 's2969', 's297', 's2970', 's2971', 's2972', 's2973', 's2974', 's2975', 's2976', 's2977', 's2978', 's2979', 's298', 's2980', 's2981', 's2982', 's2983', 's2984', 's2985', 's2986', 's2987', 's2988', 's2989', 's299', 's2990', 's2991', 's2992', 's2993', 's2994', 's2995', 's2996', 's2997', 's2998', 's2999', 's3', 's30', 's300', 's3000', 's3001', 's3002', 's3003', 's3004', 's3005', 's3006', 's3007', 's3008', 's3009', 's301', 's3010', 's3011', 's3012', 's3013', 's3014', 's3015', 's3016', 's3017', 's3018', 's3019', 's302', 's3020', 's3021', 's3022', 's3023', 's3024

In [22]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month

* new column that have only number from duration column

In [27]:
df['duration_value'] = df['duration'].str.extract(r'(\d+)').astype(int)

* new column that have only season or minute from duration column

In [30]:
df['duration_unit'] = df['duration'].str.extract(r'([A-Za-z]+)')

* create new column duration minute for ctegory movie and column season for tv shows as we have two categpry tv shows and movies

In [32]:
df['duration_min'] = df['duration_value'].where(df['category'] == 'Movie')
df['seasons'] = df['duration_value'].where(df['category'] == 'TV Show')

* for multiple country and genere we split it and keep only first occurece for better analysis

In [35]:
df['primary_country'] = df['country'].str.split(',').str[0].str.strip()
df['primary_genre'] = df['genres'].str.split(',').str[0].str.strip()

In [38]:
df.to_csv(r'D:\Data Analytics\DA_python_projects\netflix_analysis\dataset\clean_dataset.csv' , index=False)