In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("clean_data.csv")
display(df.head(5))

,chenal_group,user,session,engaged_session,avg_eng_time_per_session,engaged_session_per_user,event_per_session,engagement_rate,event_count,date,hour,year,month
0,Direct,237,300,144,47.526667,0.607595,4.673333,0.480000,1402,2024-04-16,23,2024,4
1,Organic Social,208,267,132,32.097378,0.634615,4.295880,0.494382,1147,2024-04-17,19,2024,4
2,Direct,188,233,115,39.939914,0.611702,4.587983,0.493562,1069,2024-04-17,23,2024,4
3,Organic Social,187,256,125,32.160156,0.668449,4.078125,0.488281,1044,2024-04-17,18,2024,4
4,Organic Social,175,221,112,46.918552,0.640000,4.529412,0.506787,1001,2024-04-17,20,2024,4

In [3]:
df.describe()

,user,session,engaged_session,avg_eng_time_per_session,engaged_session_per_user,event_per_session,engagement_rate,event_count,hour,year,month
count,3182.000000,3182.000000,3182.000000,3182.000000,3182.000000,3182.000000,3182.000000,3182.000000,3182.000000,3182.0,3182.000000
mean,41.935889,51.192646,28.325581,66.644581,0.606450,4.675969,0.503396,242.272470,11.807040,2024.0,4.108108
std,29.582258,36.919962,20.650569,127.200659,0.264023,2.795228,0.228206,184.440313,6.886686,0.0,0.310566
min,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2024.0,4.000000
25%,20.000000,24.000000,13.000000,32.103034,0.561404,3.750000,0.442902,103.000000,6.000000,2024.0,4.000000
50%,42.000000,51.000000,27.000000,49.020202,0.666667,4.410256,0.545455,226.000000,12.000000,2024.0,4.000000
75%,60.000000,71.000000,41.000000,71.487069,0.750000,5.217690,0.633333,339.000000,18.000000,2024.0,4.000000
max,237.000000,300.000000,144.000000,4525.000000,2.000000,56.000000,1.000000,1402.000000,23.000000,2024.0,5.000000