# business problem

* Revenue is growing but contribution margin is shrinking. The business cannot sustain this trajectory.
Leadership needs to identify the specific products, categories, or seller segments where growth is
creating losses rather than profit

In [3]:
import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings('ignore')
print(os.getcwd())

d:\Data Analytics\Marketplace Margin Leakage Detection\notebooks

In [6]:
# Define folder paths

RAW_PATH = r"D:\Data Analytics\Marketplace Margin Leakage Detection\datasets"
CLEAN_PATH = r"D:\Data Analytics\Marketplace Margin Leakage Detection\clean_datasets"

# Create cleaned folder if not exists

os.makedirs(CLEAN_PATH, exist_ok=True)


# Load all CSV files

datasets = {}

for file in os.listdir(RAW_PATH):

    if file.endswith('.csv'):

        file_path = os.path.join(RAW_PATH, file)

        df = pd.read_csv(file_path)

        datasets[file.replace('.csv', '')] = df

        print(f"{file} - Shape: {df.shape}")

olist_customers_dataset.csv - Shape: (99441, 5)
olist_geolocation_dataset.csv - Shape: (1000163, 5)
olist_orders_dataset.csv - Shape: (99441, 8)
olist_order_items_dataset.csv - Shape: (112650, 7)
olist_order_payments_dataset.csv - Shape: (103886, 5)
olist_order_reviews_dataset.csv - Shape: (99224, 7)
olist_products_dataset.csv - Shape: (32951, 9)
olist_sellers_dataset.csv - Shape: (3095, 4)
product_category_name_translation.csv - Shape: (71, 2)

In [11]:
def data_profile(df, name):

    print(f"\n{'='*50}")
    print(f"DATASET: {name}")
    print(f"{'='*50}")

    print("Rows & Columns:", df.shape)

    print("\nColumn Information:")
    print(df.info())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Records:")
    print(df.duplicated().sum())

    print("\nStatistical Summary:")
    display(df.describe().T)

for name, df in datasets.items():

    data_profile(df, name)

==================================================
DATASET: olist_customers_dataset
==================================================
Rows & Columns: (99441, 5)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
customer_zip_code_prefix,99441.0,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0

==================================================
DATASET: olist_geolocation_dataset
==================================================
Rows & Columns: (1000163, 5)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

Missing Values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate Records:
261831

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,36574.166466,30549.335710,1001.000000,11075.000000,26530.000000,63504.000000,99990.000000
geolocation_lat,1000163.0,-21.176153,5.715866,-36.605374,-23.603546,-22.919377,-19.979620,45.065933
geolocation_lng,1000163.0,-46.390541,4.269748,-101.466766,-48.573172,-46.637879,-43.767709,121.105394

==================================================
DATASET: olist_orders_dataset
==================================================
Rows & Columns: (99441, 8)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,unique,top,freq
order_id,99441,99441,e481f51cbdc54678b7cc49136f2d6af7,1
customer_id,99441,99441,9ef432eb6251297304e76186b10a928d,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:05:26,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 19:36:48,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

==================================================
DATASET: olist_order_items_dataset
==================================================
Rows & Columns: (112650, 7)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

Missing Values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
order_item_id,112650.0,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00
price,112650.0,120.653739,183.633928,0.85,39.90,74.99,134.90,6735.00
freight_value,112650.0,19.990320,15.806405,0.00,13.08,16.26,21.15,409.68

==================================================
DATASET: olist_order_payments_dataset
==================================================
Rows & Columns: (103886, 5)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
payment_sequential,103886.0,1.092679,0.706584,1.0,1.00,1.0,1.0000,29.00
payment_installments,103886.0,2.853349,2.687051,0.0,1.00,1.0,4.0000,24.00
payment_value,103886.0,154.100380,217.494064,0.0,56.79,100.0,171.8375,13664.08

==================================================
DATASET: olist_order_reviews_dataset
==================================================
Rows & Columns: (99224, 7)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None

Missing Values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Duplicate Records:
0

Statistical Summary:

                count      mean       std  min  25%  50%  75%  max
review_score  99224.0  4.086421  1.347579  1.0  4.0  5.0  5.0  5.0

==================================================
DATASET: olist_products_dataset
==================================================
Rows & Columns: (32951, 9)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

Missing Values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
product_name_lenght,32341.0,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

==================================================
DATASET: olist_sellers_dataset
==================================================
Rows & Columns: (3095, 4)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

Missing Values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate Records:
0

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
seller_zip_code_prefix,3095.0,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0

==================================================
DATASET: product_category_name_translation
==================================================
Rows & Columns: (71, 2)

Column Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

Missing Values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate Records:
0

Statistical Summary:

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

In [12]:
def clean_column_names(df):

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(' ', '_', regex=False)
        .str.replace(r'[^a-zA-Z0-9_]', '', regex=True)
    )

    return df

def remove_duplicates(df):

    before = len(df)

    df = df.drop_duplicates()

    after = len(df)

    print(f"Duplicates Removed: {before - after}")

    return df

In [13]:
def handle_missing_values(df):

    for col in df.columns:

        if df[col].dtype == 'object':

            df[col] = df[col].fillna('Unknown')

        elif pd.api.types.is_numeric_dtype(df[col]):

            df[col] = df[col].fillna(df[col].median())

    return df

def clean_text_columns(df):

    for col in df.select_dtypes(include='object').columns:

        df[col] = df[col].str.strip()

    return df

In [14]:
def standardize_missing_values(df):

    df.replace(
        ['', ' ', 'NA', 'N/A', 'null', 'NULL', 'None', '?'],
        np.nan,
        inplace=True
    )

    return df

In [15]:
# combine all function to check it 

def clean_dataset(df):

    df = df.copy()

    # 1. Standardize column names
    df = clean_column_names(df)

    # 2. Standardize missing values
    df = standardize_missing_values(df)

    # 3. Clean text columns
    df = clean_text_columns(df)

    # 4. Remove duplicates
    df = remove_duplicates(df)

    # 5. Handle missing values
    df = handle_missing_values(df)

    return df

In [16]:
cleaned_datasets = {}

for name, df in datasets.items():

    print(f"\nCleaning Dataset: {name}")

    cleaned_df = clean_dataset(df)

    cleaned_datasets[name] = cleaned_df

    print("Cleaning Completed!")

Cleaning Dataset: olist_customers_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_geolocation_dataset
Duplicates Removed: 261831
Cleaning Completed!

Cleaning Dataset: olist_orders_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_order_items_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_order_payments_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_order_reviews_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_products_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: olist_sellers_dataset
Duplicates Removed: 0
Cleaning Completed!

Cleaning Dataset: product_category_name_translation
Duplicates Removed: 0
Cleaning Completed!

In [17]:
# save all dataset 
for name, df in cleaned_datasets.items():

    output_path = os.path.join(
        CLEAN_PATH,
        f"{name}_cleaned.csv"
    )

    df.to_csv(output_path, index=False)

    print(f"{name} Exported Successfully!")

olist_customers_dataset Exported Successfully!
olist_geolocation_dataset Exported Successfully!
olist_orders_dataset Exported Successfully!
olist_order_items_dataset Exported Successfully!
olist_order_payments_dataset Exported Successfully!
olist_order_reviews_dataset Exported Successfully!
olist_products_dataset Exported Successfully!
olist_sellers_dataset Exported Successfully!
product_category_name_translation Exported Successfully!

In [18]:
# generate a clening summury report

cleaning_report = []

for name in datasets:

    raw_df = datasets[name]
    clean_df = cleaned_datasets[name]

    cleaning_report.append({

        'Dataset': name,

        'Original_Rows': len(raw_df),

        'Cleaned_Rows': len(clean_df),

        'Original_Columns': len(raw_df.columns),

        'Cleaned_Columns': len(clean_df.columns),

        'Duplicates_Remaining': clean_df.duplicated().sum(),

        'Missing_Values_Remaining': clean_df.isnull().sum().sum()

    })


report_df = pd.DataFrame(cleaning_report)

display(report_df)

,Dataset,Original_Rows,Cleaned_Rows,Original_Columns,Cleaned_Columns,Duplicates_Remaining,Missing_Values_Remaining
0,olist_customers_dataset,99441,99441,5,5,0,0
1,olist_geolocation_dataset,1000163,738332,5,5,0,0
2,olist_orders_dataset,99441,99441,8,8,0,0
3,olist_order_items_dataset,112650,112650,7,7,0,0
4,olist_order_payments_dataset,103886,103886,5,5,0,0
5,olist_order_reviews_dataset,99224,99224,7,7,0,0
6,olist_products_dataset,32951,32951,9,9,0,0
7,olist_sellers_dataset,3095,3095,4,4,0,0
8,product_category_name_translation,71,71,2,2,0,0